### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_response'

### ISSUE THREAD

**Issue by adelnr** [shakedzy/companion#50]
Hi I tried the code with a different version of Python and still am having the same issue there is no response and I can't see or hear what the ai sending hope you will fix this issue or guide us to a solution for that 
thank you 

![Screenshot 2024-03-01 at 01 55 46](https://github.com/shakedzy/companion/assets/12511083/4f95695e-6b79-43eb-ac67-232ea16f44d2)
![Screenshot 2024-03-01 at 01 55 39](https://github.com/shakedzy/companion/assets/12511083/156bb20d-eee5-4d87-825a-dc627aacb48e)

**Comment by shakedzy** [comment]
Seems like the app wasn't initiated properly. Make sure to follow all the installation process as mentioned in the docs.

**Comment by trbella** [comment]
I am with exactly the same problem. I followed the instructions (for local and mobile) and did not work.

**Comment by shakedzy** [comment]
Please share the logs from the terminal

**Comment by trbella** [comment]
> Please share the logs from the terminal

I am sorry. It was my bad. I just forgot to configure the setup file in the first use. After that it worked fine. Sometimes the text from the tutor was not read completely by the google text to speech, but after reboot it worked.
Maybe this is the problem of @adelnr

**Comment by adelnr** [comment]
hi I still have the same issue I tried it on Codespace and still having an issue can guide me to fix it I
![Screenshot 2024-03-05 at 11 26 10](https://github.com/shakedzy/companion/assets/12511083/8485eb85-53ce-4f1b-8e05-764e32a8d784)
![Screenshot 2024-03-05 at 11 24 57](https://github.com/shakedzy/companion/assets/12511083/da0acb8c-f3d0-4d67-8259-cb29390edfbe)
![Screenshot 2024-03-05 at 11 24 46](https://github.com/shakedzy/companion/assets/12511083/702f9703-ae55-412a-9d14-761199cd850b)
 will be [thankful

**Comment by adelnr** [comment]
> > Please share the logs from the terminal
> 
> I am sorry. It was my bad. I just forgot to configure the setup file in the first use. After that it worked fine. Sometimes the text from the tutor was not read completely by the google text to speech, but after reboot it worked. Maybe this is the problem of @adelnr

Hi Trbella how did you configure the setup

**Comment by shakedzy** [comment]
It's in the docs: https://shakedzy.xyz/companion/run/

> **Launching for the first time**
> If this is the first time you run the app, you'll need to first configure your tutor. To do so, click Settings () on the top-left corner of the main screen, or go to http://127.0.0.1:5000/setup.

**Comment by adelnr** [comment]
I did that  i chose what language i want and what sound and saved it but still have the same issue
